### ISSUE TITLE
How is the signature image stored?

### ISSUE THREAD

**Issue by bartrikers** [mendixlabs/signature#4]
Hi,

I wanted to update from the 'old' signature widget to the new but I can't seem to figure out how the signature image is stored?

I've included the widget in a dataview of an object that is a specialization of System.Image.

Setting the signature works, and also the HasSignature boolean is set to true, but when I invoke my save microflow, the Image.HasContents attribute is false, indicating the image has no content.

![afbeelding](https://user-images.githubusercontent.com/23105910/49733232-409fdf00-fc81-11e8-9671-eaef591b9dd2.png)

How can I access the signature, either as a Base64 string or as the Image content?

Kind regards,
Bart Rikers

**Comment by SamuelMuloki** [comment]
Hello @bartrikers you can access it as image content, add a page with a template grid, and connect it to your entity as a data source, you'll be able to see your previously saved signatures.
cheers Samuel

**Comment by bartrikers** [comment]
Hi Samuel,

Thanks for the reply, but I still can't get it to work. My question is: how can I access the image in a microflow?

I've included a testproject (rename .zip to .mpk) or check https://signaturetest-sandbox.mxapps.io

[SignatureTest.zip](https://github.com/mendixlabs/signature/files/2671370/SignatureTest.zip)


- Open and run the testproject, click New in the datagrid to create a new document ( and the underlying signature object, which is a specialization of System.Image)
- Set the signature: you will see that the Reset button will appear, indicating the HasSignature boolean is set to true
- Now press save, you will get the message ' signature is set but the Image object has no content.'. This is because in the underlying save microflow (IVK_Document_Save) there is a validation, and the Signature.HasSignature is true, but the Signature.HasContent is false, indicating the content of the image is not set.
![afbeelding](https://user-images.githubusercontent.com/23105910/49860997-30ac0a80-fdfb-11e8-92db-e1e873f06b2a.png)

- After you've saved, at the bottom of the homepage there is a template grid, this is connected to the signature object as you said, but as you can see by the red cross, the signature itself is not visible.
![afbeelding](https://user-images.githubusercontent.com/23105910/49861025-415c8080-fdfb-11e8-9ecd-b6ae51cd4b6d.png)

- Also, if you open the newly created document again, you will not see the Signature.
![afbeelding](https://user-images.githubusercontent.com/23105910/49861052-4e796f80-fdfb-11e8-8972-28eadeb23265.png)

How can I get this to work? And how can I access the image content in a microflow?



Thanks!

Kind regards,
Bart

**Comment by Andries-Smit** [comment]
The fix is now available trough the app store, in v1.0.1
https://appstore.home.mendix.com/link/app/107984/
