### ISSUE TITLE
Widget does not show previous set signature

### ISSUE THREAD

**Issue by bartrikers** [mendixlabs/signature#6]
Hi,

After my [previous issue](https://github.com/mendixlabs/signature/issues/4) has been fixed, I can now successfully save the signature (thanks!) but I encountered another problem:

When I save a signature, and then open it again, the previously saved signature is not visible in the widget.

To reproduce, check out my test project at https://signaturetest-sandbox.mxapps.io
- add a new signature and save it.
- now open the saved signature by clicking the Edit button. You'll see that the widget stays blank, even though you'd expect to see the signature previously set here.

Kind regards,
Bart

**Comment by Andries-Smit** [comment]
Hi Bart,

Its correct that you do not see the previous signature.  For more information see the read me:
https://github.com/mendixlabs/signature#notion--limitations

Cheers, Andries

**Comment by Andries-Smit** [comment]
The repository has moved, this feature request also moved to our internal backlog.
