### ISSUE TITLE
Please dont set the name if it's already set

### ISSUE THREAD

**Issue by bartrikers** [mendixlabs/signature#7]
Now, when you set the signature, the name of the Image object is automatically set to signature[randonnr?].png, but sometimes, we want to control the name of the file.

In our case, we set the name upon creation of the Image object, but now, this name will be overwritten by the signature widget, So please only automatically set the name in case the Name attribute is empty, otherwise keep the name that is already set.

**Comment by Andries-Smit** [comment]
Hi Bart,

Thanks you for the feature request. We will take into consideration. For now you can change the name in the workflow when processing the document.
 
Cheers, Andries

**Comment by Andries-Smit** [comment]
Feature implemented in version 1.0.2 
available trough the app store https://appstore.home.mendix.com/link/app/107984/
